services:
    redwood.user_provider:
        class: Redwood\Service\User\UserProvider
        arguments:    [@service_container]

    redwood.authentication.success_handler:
        class: Redwood\WebBundle\Handler\AuthenticationSuccessHandler
        parent: security.authentication.success_handler

    redwood.logout.success_handler:
        class: Redwood\WebBundle\Handler\LogoutSuccessHandler
        parent: security.logout.success_handler


security:
    encoders:
        Redwood\Service\User\CurrentUser: sha256

    providers:
        custom_provider:
            id: redwood.user_provider

    role_hierarchy:
        ROLE_EDITOR:     ROLE_USER
        ROLE_ADMIN:       ROLE_EDITOR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        main:
            pattern:    /.*
            form_login:
                login_path: login
                check_path: login_check
                use_referer: true
                # failure_handler: redwood.authentication.failure_handler
                success_handler: redwood.authentication.success_handler
            remember_me:
                key: "%secret%"
                lifetime: 2592000
                path: /
                domain: ~
                always_remember_me: true
            logout:
                path:   logout
                target: /
                success_handler: redwood.logout.success_handler
            anonymous:  true

    access_control:
        - { path: ^/inbox, role: ROLE_USER }
        - { path: ^/admin/setting, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
